language: java

jdk:
  - oraclejdk8

services:
  - docker


deploy:
  - provider: script
    script:
      - mvn clean package
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -f docker/Dockerfile -t spireet/gerald:importer .
      - docker push spireet/gerald:importer
    on:
      branch: master

  - provider: script
    script:
      - mvn clean package
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -f docker/Dockerfile -t spireet/gerald:importer-integ .
      - docker push spireet/gerald:importer-integ
    on:
      branch: develop