message: Greetings from importer application
application:
  api:
    uri: https://avisto.gcn-eibp.com/api
    key: 3a403b7b-ffaa-4da8-89fa-c7f59bd62e8a
  scheduling:
    enabled: true
  task:
    customeragreement:
      source: /tmp/CA
      cron: "0 * * * * ?"

logging:
  level:
    root: INFO
    com.greencom.empower.importer: DEBUG
#    org.apache.http: DEBUG

# Enable/disable job run on application's startup
spring.batch.job.enabled: false

spring:
  profiles:
    active: prod
---

spring:
  profiles: dev


---

spring:
  profiles: prod

---

spring:
  profiles: test
  customeragreement:
    source: /test/resources/inputs/customer_agreements
